name: Publish bun Docker Image

on:
  workflow_dispatch:
  push:
    tags: [ 'v[0-9]+.[0-9]+.?[0-9]*' ] # Push events to matching v*, i.e. v1.0, v20.15.10    
    
jobs:    
  upload-dockerhub:
    runs-on: ubuntu-latest
    env:
      DOCKER_ID: dvlprtech
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get code and version to build
        uses: actions/checkout@v3
      - run: |
              export TAG_VERSION=$(cat ./last-bun-version.txt)
              echo "APP_VERSION=${TAG_VERSION#*v}" >> $GITHUB_ENV
              echo "APP_NAME=bun" >> $GITHUB_ENV
      - run: echo "DOCKER_IMAGE=${{ env.DOCKER_ID }}/${{ env.APP_NAME }}" >> $GITHUB_ENV
      - run: echo App ${{env.DOCKER_IMAGE}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.APP_VERSION }} , ${{ env.DOCKER_IMAGE }}:latest
      - run: echo "🍏 This job's status is ${{ job.status }}."

