name: Publish bun canary Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron:  '5 */12 * * *'
    
jobs:    
  upload-dockerhub:
    runs-on: ubuntu-latest
    env:
      DOCKER_ID: dvlprtech
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get code and version to build
        uses: actions/checkout@v3
      - run: |
              export TAG_VERSION=$(cat ./last-bun-version.txt)
              echo "APP_VERSION=${TAG_VERSION#*v}" >> $GITHUB_ENV
              echo "APP_NAME=bun" >> $GITHUB_ENV
      - run: echo "DOCKER_IMAGE=${{ env.DOCKER_ID }}/${{ env.APP_NAME }}" >> $GITHUB_ENV
      - run: echo App ${{env.DOCKER_IMAGE}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          labels: "version=${{ env.APP_VERSION }}-canary"
          push: true
          no-cache: true
          build-args: release=canary
          tags: ${{ env.DOCKER_IMAGE }}:canary
      - run: echo "🍏 This job's status is ${{ job.status }}."

