name: Get latest release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch release version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://api.github.com/repos/oven-sh/bun/releases/latest | \
          jq -r ".tag_name" > last-bun-version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          export TAG_VERSION=$(cat last-bun-version.txt)
          export VERSION=${TAG_VERSION#*v}
          git config --global user.email "dvlprtech@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "v$VERSION"
          git push
          git tag -a "v$VERSION" HEAD -m "v$VERSION"
          git push origin "v$VERSION"
      - name: Test workflow call
        run: |
          gh workflow run docker-publish.yml
          
